name: songbox-client

windows:
  - editor:
      layout: main-horizontal
      # Synchronize all panes of this window, can be enabled before or after the pane commands run.
      # 'before' represents legacy functionality and will be deprecated in a future release, in favour of 'after'
      # synchronize: after
      panes:
        - nvim
        -
  - server:
      layout: even-vertical
      panes:
        - yarn start
        -
  - git:
      layout: even-vertical
      panes:
        - lazygit
        -
